### ISSUE TITLE
shape ys_ and yd differs

### ISSUE THREAD

**Issue by anujgupta82** [suriyadeepan/rnn-from-scratch#2]
shape of ys_ is (?)
while shape of ys is (128, 20) 

Am I missing something ?

**Comment by suriyadeepan** [comment]
I apologize for the delayed reply. Hope it's still useful.

I'm flattening `ys` to shape (128*20) while feeding it to graph during execution. .

https://github.com/suriyadeepan/rnn-from-scratch/blob/master/gru.py#L116
